# config/corne_left.conf
# Left keyboard peripheral - connects to dongle via BLE

CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_BACKLIGHT=n

CONFIG_ZMK_SLEEP=y
#CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

CONFIG_ZMK_DISPLAY=y 

CONFIG_ZMK_BATTERY_REPORTING=y

CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
# No longer central - this side connects to the dongle

CONFIG_ZMK_EXT_POWER=y