# Uncomment the following lines to enable the Corne RGB Underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=0
CONFIG_ZMK_RGB_UNDERGLOW_LIGHTNESS=0.5
CONFIG_ZMK_RGB_UNDERGLOW_SATURATION=1.0
CONFIG_ZMK_RGB_UNDERGLOW_SPEED=0
CONFIG_ZMK_RGB_UNDERGLOW_EFFECT_STATIC=y

# Test: nur LED 0 leuchten lassen
CONFIG_ZMK_RGB_UNDERGLOW_PIXELS="0"
CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_BACKLIGHT=y
CONFIG_ZMK_BACKLIGHT_ON_START=y
CONFIG_ZMK_BACKLIGHT_BRIGHTNESS=255

backlight {
    pixel-range = <6 22>;  # Beispiel: 6 Underglow LEDs, danach 22 Key LEDs
};